<?php
require __DIR__.'/../app/bootstrap.php';
$edit=max(0,(int)($_GET['edit']??0));
if($edit&&!admin()){header('Location: admin.php');exit;}
?>
<!doctype html>
<html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rozdání a postřehy • BK Praha</title>
<link rel="stylesheet" href="style.css"><meta name="csrf-token" content="<?=h($_SESSION['csrf'])?>"></head><body data-edit="<?= $edit ?>">
<?php require __DIR__.'/../app/header.php'; ?>
<main><div class="intro"><div class="eyebrow">Rozdání a postřehy</div><h1>Každé rozdání má svůj příběh</h1><p class="lead">Zadejte karty, přidejte dražbu a podělte se o svůj pohled.</p></div>
<div class="toolbar"><button id="sample">Vyzkoušet ukázku</button><button id="export">Uložit do souboru</button><button id="import">Načíst ze souboru</button><button id="import-pbn">Importovat PBN</button><input id="pbn-file" type="file" accept=".pbn" hidden><button id="reset">Nové rozdání</button><button class="mobile-preview" id="jump">Zobrazit náhled ↓</button><span class="save" id="saved" role="status"></span><input id="file" type="file" accept=".json,application/json" hidden></div><p id="toast" role="status"></p>
<section id="pbn-panel" class="panel" hidden><h2>Vyberte rozdání z PBN</h2><p id="pbn-summary" class="small"></p><label for="pbn-select">Rozdání</label><select id="pbn-select"></select><p id="pbn-warning" role="status"></p><div class="actions"><button id="pbn-load" class="primary">Načíst vybrané rozdání</button><button id="pbn-cancel">Zrušit</button></div><p class="hint">Načtou se karty, rozdávající, stav her a případná dražba. Váš název, jméno a text se nezmění.</p></section><div class="layout"><div class="editor">
<section class="panel"><div class="eyebrow">01 / Karty</div><h2>Co kdo držel?</h2><div class="row"><div><label for="dealer">Rozdávající</label><select id="dealer"><option value="N">North</option><option value="E">East</option><option value="S">South</option><option value="W">West</option></select></div><div><label for="vul">Ve druhé hře</label><select id="vul"><option value="none">none</option><option value="NS">NS</option><option value="EW">EW</option><option value="both">all</option></select></div></div>
<div class="hands" id="hands" aria-label="Vyberte ruku"></div><div id="entries"></div><p class="hint">Pište např. AKJ109 nebo AKJT9. Desítka může být 10 i T. Prázdné pole zatím znamená nezadané karty.</p><button id="fill">Doplnit zbývající karty do této ruky</button><div id="validation" aria-live="polite"></div><details><summary>Nebo vyberte karty klikáním</summary><p class="hint">Karty se přidávají do vybrané ruky. Opětovným kliknutím kartu odeberete; karty v jiné ruce jsou nedostupné.</p><div id="deck"></div></details></section>
<section class="panel"><div class="eyebrow">02 / Dražba</div><h2>Jak se dražilo?</h2><div id="auction-editor"></div><p id="turn" class="small" aria-live="polite"></p><div class="levels" id="levels" aria-label="Stupeň závazku"></div><div class="strains" id="strains"></div><div class="actions"><button id="pass">Pas</button><button id="double">Kontra</button><button id="redouble">Rekontra</button><button id="undo">↶ Zpět</button></div><p class="hint">Vyberte stupeň a barvu. Dražbu můžete nechat prázdnou nebo uvést jen její začátek.</p></section>
<section class="panel"><div class="eyebrow">03 / Váš příspěvek</div><h2>Vyprávějte příběh.</h2><div class="field"><label for="title">Název příspěvku</label><input id="title" maxlength="140" placeholder="Třeba: Devátý zdvih se schovával v trefech"></div><div class="field"><label for="author">Jméno autora</label><input id="author" maxlength="100" autocomplete="name" placeholder="Jméno a příjmení"></div><label for="body">Text příspěvku</label><textarea id="body" maxlength="20000" placeholder="Co vás na rozdání zaujalo? Jak se hrálo? Nebo na co byste se chtěli ostatních zeptat?"></textarea><p class="hint">Náhled se mění průběžně. Text se zobrazuje přesně tak, jak ho napíšete.</p></section>
<section class="panel"><div class="trap" aria-hidden="true"><label for="website">Web</label><input id="website" tabindex="-1" autocomplete="off"></div>
<?php if($edit):?><label for="post-status">Stav příspěvku</label><select id="post-status"><option value="pending">Čeká na schválení</option><option value="published">Zveřejnit</option><option value="rejected">Odmítnout / skrýt</option></select><p><a href="admin.php">Zpět do správy</a></p><?php else:?><p>Odesláním předáváte příspěvek klubu ke kontrole a zveřejnění včetně jména autora.</p><?php endif;?>
<button id="submit-post" class="primary"><?= $edit?'Uložit změny':'Odeslat ke schválení' ?></button><p id="submission-result" role="status" aria-live="polite"></p></section></div><aside class="panel preview" id="preview"><div class="eyebrow">Náhled příspěvku</div><h2 id="preview-title"></h2><div class="author" id="preview-author"></div><div class="board" id="board"></div><div id="preview-auction"></div><div class="prose" id="preview-body"></div><div class="footnote">Příspěvek se na webu zobrazí po schválení. Zálohu rozpracovaného zadání si můžete stáhnout tlačítkem „Uložit do souboru“.</div></aside></div></main><?php require __DIR__.'/../app/footer.php'; ?>
<script src="editor.js" defer></script></body></html>
